apiVersion: v1
kind: Service
metadata:
  name: jayne-flask-service
spec:
  type: LoadBalancer
  selector:
    app: jayne-flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jayne-flask-deployment
  labels:
    app: jayne-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jayne-flask 
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
      app: jayne-flask
    spec:
      containers:
      - name: jayne-flask-container
        image: eu.gcr.io/lbg-mea-17/jayne-python-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080