apiVersion: v1
kind: Service
metadata:
  name: jayne-api-service
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jayne-api-deployment
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: jayne-api-container
        image: eu.gcr.io/lbg-mea-17/jayne-python-api:{{BUILD_VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080