apiVersion: v1
kind: Service
metadata:
  name: jayne-api-service
  labels:
    app: jayne-api
spec:
  type: LoadBalancer
  selector:
    app: jayne-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{PORT}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jayne-api-deploy
  labels:
    app: jayne-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jayne-api
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:
        app: jayne-api
    spec:
      containers:
      - image: {{GCR_URL}}\/{{IMAGE_NAME}}:{{BUILD_VERSION}}
        name: jayne-api-container
        imagePullPolicy: Always
        ports:
        - containerPort: 8080